{% set name = "snowplow-tracker" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowplow_tracker-{{ version }}.tar.gz
  sha256: 95d8fdc8bd542fd12a0b9a076852239cbaf0599eda8721deaf5f93f7138fe755

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.25.1,<3.0
    - types-requests >=2.25.1,<3.0
    - typing_extensions >=3.7.4

test:
  imports:
    - snowplow_tracker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://snowplow.io
  dev_url: https://github.com/snowplow/snowplow-python-tracker
  doc_url: https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/python-tracker/
  summary: Snowplow event tracker for Python. Add analytics to your Python and Django apps, webapps and games.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
